name:                aeson-stream
version:             0.1.0.0
github:              "mzabani/aeson-stream"
license:             BSD3
author:              "Marcelo Zabani"
maintainer:          "mzabani@gmail.com"
copyright:           "2022 Marcelo Zabani"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mzabani/aeson-stream#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- streaming
- text

ghc-options:
  - -O2

default-extensions:
  - BangPatterns
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - LambdaCase
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - TypeFamilies
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilyDependencies
  - ViewPatterns

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wpartial-fields

tests:
  aeson-stream-tests:
    main: Main.hs
    source-dirs: test
    system-build-tools:
      - hspec-discover
    ghc-options:
      - -Wincomplete-uni-patterns
    dependencies:
      - aeson-stream
      - hspec